name: Build releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { goos: "linux", goarch: "amd64" }
          - { goos: "linux", goarch: "arm" }
          - { goos: "linux", goarch: "arm64" }
          - { goos: "freebsd", goarch: "amd64" }
          - { goos: "windows", goarch: "amd64" }
      fail-fast: true

    name: Build ${{ matrix.goos }} ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          TARGET: udp-proxy-${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          mkdir -p $TARGET
          go build -v -o $TARGET/udp-proxy .
          cp LICENSE README.md $TARGET
          tar -czf $TARGET.tar.gz $TARGET

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.tar.gz
